### ISSUE TITLE
get_address_with_tags

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-openapi#1]
At the moment this is a bit misleading and it remains unclear why there are two interfaces

get_address_with_tags
list_address_tags

I propose to change it as follows

get_address (returns properties of an address; if an optional "includeTags" parameter is passed, it also returns the tags)

The same should apply for the entity level

**Comment by behas** [comment]
Can we return tags optionally:

/btc/address/18NSAybFEhLa6AG3gxEN1hiaRJoSvvbnDb -> returns "address" properties only
/btc/address/18NSAybFEhLa6AG3gxEN1hiaRJoSvvbnDb?includeTags=True -> also returns associated tags ("address_with_tags")

Often tags are not needed and not requesting them saves a backend query -> speeds up things.

**Comment by myrho** [comment]
Done!
