### ISSUE TITLE
Inconsistent naming of method

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-openapi#10]
The naming scheme is somehow inconsistent with the API

```
list_entity_neighbors
list_entity_addresses
...
```

`list_tags_by_entity` should then be named `list_entity_tags``
`list_tags_by_address` should be `list_address_tags`

**Comment by myrho** [comment]
I think the rationale behind this was that `list_tags_by_entity` returns entity AND address tags. `list_entity_tags` sounds like returing just entity tags though. 

`list_tags_by_address` however could be named `list_address_tags` because it just returns address_tags.
