### ISSUE TITLE
Provide an interface for retrieving tags for a list of addresses / entities

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-openapi#15]
Problem: client has a list of entities (or addresses) and would like to retrieve tags for these entities (addresses) in a batch manner.

Proposed solution:

`/{currency}/addresses/tags?ids=[list of strings]`
`/{currency}/addresses/tags.csv?ids=[list of strings]`
`/{currency}/entities/tags?ids=[list of ints]`
`/{currency}/entities/tags?ids.csv=[list of ints]`

**Comment by myrho** [comment]
Fixed through bulk interface.
