### ISSUE TITLE
Entity tags vs. Entity address tags

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-openapi#5]
In the underlying data model [1] we distinguish between

a.) tags directly assigned to entities (table cluster_tags)
b.) the accumulated address tags assigned to entities (table cluster_address_tags)

We could expose this on the REST interface as follows

/{currency}/entities/{entity}/tags -> returns a.)
/{currency}/entities/{entity}/address_tags -> returns b.)

OR

/{currency}/entities/{entity}/tags?type=address|entity -> returns a.) or b.)

[1] See schema https://github.com/graphsense/graphsense-transformation/blob/develop/scripts/schema_transformed.cql

**Comment by myrho** [comment]
Implemented as
`/{currency}/entities/{entity}/tags?level=address|entity` -> returns a.) or b.)
`level` as a parameter name ok? Since the type of both is identical actually.
